create extension if not exists pgcrypto;
create table if not exists public.sessions(id uuid primary key default gen_random_uuid(),slug text unique not null,title_tr text not null default '',title_en text not null default '',description_tr text not null default '',description_en text not null default '',is_open boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.groups(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.sessions(id) on delete cascade,name_tr text not null default '',name_en text not null default '',description_tr text not null default '',description_en text not null default '',sort_order int not null default 0);
create table if not exists public.dimensions(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.sessions(id) on delete cascade,name_tr text not null default '',name_en text not null default '',description_tr text not null default '',description_en text not null default '',sort_order int not null default 0);
create table if not exists public.responses(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.sessions(id) on delete cascade,group_id uuid not null references public.groups(id) on delete cascade,answers jsonb not null,device_token text,created_at timestamptz not null default now());
alter table public.sessions enable row level security; alter table public.groups enable row level security; alter table public.dimensions enable row level security; alter table public.responses enable row level security;
create policy "public read sessions" on public.sessions for select using (true); create policy "public read groups" on public.groups for select using (true); create policy "public read dimensions" on public.dimensions for select using (true); create policy "public read responses" on public.responses for select using (true);
create policy "public insert responses" on public.responses for insert with check (exists(select 1 from public.sessions s where s.id=session_id and s.is_open=true));
create policy "admin sessions" on public.sessions for all to authenticated using (true) with check (true); create policy "admin groups" on public.groups for all to authenticated using (true) with check (true); create policy "admin dimensions" on public.dimensions for all to authenticated using (true) with check (true); create policy "admin responses" on public.responses for all to authenticated using (true) with check (true);
